### ISSUE TITLE
Unable to remove unsupported parameters

### ISSUE THREAD

**Issue by fraenki** [oxc/puppet-postfix#3]
Using this module it is possible to configure parameters that are unsupported by the installed postfix. However, it seems to be impossible to remove these parameters:

```
Error: /Stage[main]/Resources[postconf]: Failed to generate additional resources using 'generate':
  Parameter parameter failed on Postconf[/usr/sbin/postconf:
    warning: /etc/postfix/main.cf: unused parameter: smtputf8_enable]:
    Invalid value "/usr/sbin/postconf: warning: /etc/postfix/main.cf: unused parameter: smtputf8_enable".
  Valid values match /^([^\/]+::)?[a-zA-Z0-9]+(?:_[a-zA-Z0-9]+)*$/.
```

In this example I've tried to configure a parameter on postfix 2.x which was only introduced in postfix 3.x.
Any idea how to properly remove these parameters with your module? :)

**Comment by oxc** [comment]
For the record, the problem is that puppet providers do not support defining commands that do not munge stdout and stderr output (see https://github.com/puppetlabs/puppet/blob/master/lib/puppet/provider.rb#L259). This causes `postconf -n` output to contain warnings printed to stderr, as can be seen in the quoted error message.

We can either depend on/hack around private puppet API, or fully duplicate (as in copy&paste) the CommandDefiner / Provider#has_command system.

**Comment by oxc** [comment]
@fraenki please test again with current master

**Comment by fraenki** [comment]
@oxc It removes the Puppet error, which is all I want. Thanks! :+1: 
But the unsupported parameter remains in Postfix' `main.cf`.

**Comment by oxc** [comment]
> But the unsupported parameter remains in Postfix' main.cf.

I cannot confirm that. Are you purging the resources using `resource { postconf: purge => true }`?

**Comment by fraenki** [comment]
> I cannot confirm that.

Solved. It was a configuration issue on my side. Now the parameter is removed as expected.
